### ISSUE TITLE
<title> not loaded

### ISSUE THREAD

**Issue by soichih** [visualfanatic/vue-svg-loader#104]
I have <title> tags inside <path> to show tooltip info when I hover on top of the <path>

```
  <path id="c51685" d="m850.8 262.27 0.0709 0.0766 0.31723 0.0248 5e-3 0.17325 0.25994 0.0428 0.174 0.12079 0.0493-0.25359 5.3e-4 -0.17754-0.19412-0.20035-0.23357-2e-3 -0.28468 7e-3z">
    <title>Manassas Park, VA</title>
  </path>
```

When I load this SVG using vue-svg-loader, I don't see the <title> object loaded for <path>. Is this by design? Is there a way to retain the <title>?

**Comment by OziOcb** [comment]
I have the same issue.  I don't see `` <title>`` and ``<desc>`` after load.

I would appreciate it if someone finds the solution to this issue.

**Comment by benface** [comment]
That's because the loaded SVGs are automatically optimized with [SVGO](https://github.com/svg/svgo). The solution is to either disable SVGO, or [the specific plugin that removes the title](https://github.com/svg/svgo/blob/master/plugins/removeTitle.js). You can do so like this:

Disable SVGO:
```js
// webpack.config.js

module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: [
          'babel-loader',
          'vue-svg-loader',
        ],
        options: {
          svgo: false,
        },
      },
    ],
  },
};
```

Disable `removeTitle`:
```js
// webpack.config.js

module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: [
          'babel-loader',
          'vue-svg-loader',
        ],
        options: {
          svgo: {
            plugins: [{ removeTitle: false }],
          },
        },
      },
    ],
  },
};
```

If you're using Vue CLI, the syntax would be:
```js
module.exports = {
  chainWebpack: (config) => {
    const svgRule = config.module.rule('svg');

    svgRule.uses.clear();

    svgRule
      .use('babel-loader')
      .loader('babel-loader')
      .end()
      .use('vue-svg-loader')
      .loader('vue-svg-loader')
      .options({
        svgo: {
          plugins: [{ removeTitle: false }],
        },
      });
  },
};
```

**Comment by damianstasik** [comment]
@soichih have you tried solution posted by @benface? Please let me know if are still having some issues with the loader.
