### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by thestevelavigne** [visualfanatic/vue-svg-loader#116]
New to Vue.  Used the CLI to create a new project, installed vue-svg-loader, added the example to my app.

I ensured that vue.config.js has the correct snippet.

I continue to get the following error:

* ./public/offices/opin_office.svg in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Map.vue?vue&type=script&lang=js&

Any help would be great.

**Comment by damianstasik** [comment]
@thestevelavigne do you still have the issue? Sorry for the delayed response!
