### ISSUE TITLE
v0.16.0 update breaks SVG imports

### ISSUE THREAD

**Issue by vvanpo** [visualfanatic/vue-svg-loader#121]
Since upgrading from v0.15.0 to v0.16.0, my Webpack builds are flooded with the following types of warnings, and the resulting components throw TypeErrors:

```
"export 'default' (imported as 'Foo') was not found in '.../foo.svg'
```

My Webpack configuration is as described in the documentation, and it was working in v0.15.0.

**Comment by damianstasik** [comment]
@vvanpo do you still have the issue? If that is the case could you try `vue-svg-loader@beta` with [the updated configuration](https://github.com/visualfanatic/vue-svg-loader/tree/dev)?

**Comment by vvanpo** [comment]
@visualfanatic it appears to have fixed itself, I had my version pinned at `0.15.0` since opening this issue, but if I install `0.16.0` now (which also upgrades `svg-to-vue` to version `0.7.0`) I no longer get errors.

**Comment by vvanpo** [comment]
Using `0.17.0-beta.1` and swapping out `babel-loader` for `vue-loader` in my configuration also seems to work.

**Comment by DamianMullins** [comment]
Can confirm that `v0.16.0` with `vue-loader` works for me.

**Comment by DamianMullins** [comment]
Actually, the SVGs weren't loading correctly in `v0.16.0` when I ran my application, `v0.17.0-beta.1` is all good.
