### ISSUE TITLE
Why do i get this error? Cannot assign to read only property 'exports' of object

### ISSUE THREAD

**Issue by N1njaCat** [visualfanatic/vue-svg-loader#135]
I use as you wrote but why do I get this error?
http://joxi.ru/v29nkbziz5yqgA
http://joxi.ru/DmB0MK5tz7LBbA
http://joxi.ru/brRpkqyTY9vdk2

**Comment by N1njaCat** [comment]
I did vue upgrade common and now its work!

**Comment by damianstasik** [comment]
In case if you stumble upon more issues please report them here, thanks!
