### ISSUE TITLE
0.17.0-beta.1 in vue3 failed

### ISSUE THREAD

**Issue by zhangtaoBqteam** [visualfanatic/vue-svg-loader#138]
version: 0.17.0-beta.1
vue-version: vue 3.0 beta

I create the vue3 project through vue-cli, and follow the document to use the loader, but some errors occur when i use it

here is the configuration in vue.config.ts
```typescript
module.exports = {
  chainWebpack: (config) => {
    const svgRule = config.module.rule('svg');
    svgRule.uses.clear();
    svgRule
      .use('vue-loader')
      .loader('vue-loader-v16') // or `vue-loader-v16` if you are using a preview support of Vue 3 in Vue CLI
      .end()
      .use('vue-svg-loader')
      .loader('vue-svg-loader');
  }
};
``` 
the usage in App.vue
![image](https://user-images.githubusercontent.com/43007011/91375176-8aad6780-e84c-11ea-81b8-84a3640687d8.png)

then the error occur in broswer
![image](https://user-images.githubusercontent.com/43007011/91375221-aadd2680-e84c-11ea-8b7c-9c45dd43d55d.png)

**Comment by zhangtaoBqteam** [comment]
Here is the reproduction https://github.com/zhangtaoBqteam/feedback

**Comment by syuilo** [comment]
I have the same problem. Why was it closed?

**Comment by arcs-** [comment]
this is still an issue
