### ISSUE TITLE
Update dependency of svgo to at least version 1.0.0

### ISSUE THREAD

**Issue by ferrybig** [visualfanatic/vue-svg-loader#17]
Since svgo 1.0.0, there is a plugin called inlineStyles, the basically copied the styling from the style tags to the svg itself. This is needed as some editors like illustrator exports the svg using this inline styling.

Because vue-svg-loader forces its dependencies on svgo, there is no way to load svg files exported by illustrator, unless, you manually add svgo loader in front of the webpack loader line.

**Comment by visualfanatic** [comment]
Done in v0.5, thanks!
