### ISSUE TITLE
'use strict' doesn't like with(this)

### ISSUE THREAD

**Issue by realtruckjoshdeltener** [visualfanatic/vue-svg-loader#18]
We are using this lib and are combining it with other JS resources.  The problem is those resources are 'use strict' and so the build blows up on the svg's because the render function contains "with(this)" .. I know this is probably coming from one of your dependencies, but it sure would be nice if your system handled it.  I don't think the rendered functions even use 'this' so maybe you could just strip it.

**Comment by chenmach** [comment]
vue-template-compiler uses the with(this) syntax. change it there seems to be a hard job .
For our simple case of svg components , strip out the "with(this)" and use regular "this" seems to work.
you can take a look at https://github.com/chenmach/vue-svg-loader/commit/d13b3aceebcb6217b87ebfdc54362d31295be004
Im using it on my project - and it works for me

**Comment by visualfanatic** [comment]
@realtruckjoshdeltener @chenmach In v0.5.0 I've made some changes to the compiling process and now the end result doesn't contain the `with` statement.
