### ISSUE TITLE
Error when loading svg file.

### ISSUE THREAD

**Issue by Hjarnmastara** [visualfanatic/vue-svg-loader#19]
Hi,

After adding a svg through your webpack plugin it displays correctly but yet triggers the following error in the console:

Error: <path> attribute d: Expected number, "…6.81h9.51v22.19aNaN NaN 0 0 
It's at el.setAttribute(key, value); from vue.esm.js.

Any idea what is causing this?

Kind regards,
Ward

**Comment by visualfanatic** [comment]
Could you share the SVG that is causing this error?

**Comment by visualfanatic** [comment]
@Hjarnmastara?

**Comment by visualfanatic** [comment]
If you still have a problem, please reopen this issue, I am closing it for now.
