### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by doooooit** [visualfanatic/vue-svg-loader#190]
The latest version of this project is 0.16.0, it doesn't work on my project unless I upgrade to 0.17.0-beta.2
But this version was released two years ago, is this project still being maintained?

**Comment by Excalibaard** [comment]
Doesn't seem like it's being updated anymore. I ended up switching to `svgo-loader` for handling my svgo process and a custom loader to do the conversion to a Vue component.

https://github.com/visualfanatic/vue-svg-loader/issues/156#issuecomment-1119513016

**Comment by bjornharrtell** [comment]
I can recommend https://github.com/jpkleemans/vite-svg-loader

**Comment by kylefarris** [comment]
@doooooit Using vue2 with webpack 5 I can't even get the beta running anymore 👎🏼

**Comment by ndrscodes** [comment]
@doooooit we created a maintained fork over at https://github.com/gammacommunications/vue-svg-loader-2, I've already fixed quite a few issues there. The package is also available via npm at https://www.npmjs.com/package/vue-svg-loader-2

**Comment by seyfer** [comment]
this is a good alternative https://github.com/shrpne/vue-inline-svg
