### ISSUE TITLE
Documentation: remove other svg loaders

### ISSUE THREAD

**Issue by derhedwig** [visualfanatic/vue-svg-loader#22]
Hi!
Just tried vue-svg-loader.
I started my project via `vue init webpack`, which had put 
```
test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
loader: 'url-loader',
```
in my `webpack.base.conf.js`. I had to remove 'svg' from it, to make vue-svg-loader work.

I'm a novice with webpack, but I presume others might have the same problem, so please include it in your README.md

**Comment by H3xx3n** [comment]
Hi. Same for me. But I also need to still have url loader for other .svg files a part for the ones used by vue.
Is there a way to test only the files that are required inside vue app entry?

**Comment by sam3d** [comment]
Indeed! Webpack performs loader tests from [top to bottom](https://webpack.js.org/concepts/loaders/).

**Comment by visualfanatic** [comment]
Thank you @derhedwig! I added the note in the configuration section in the docs:
https://vue-svg-loader.js.org/#configuration
