### ISSUE TITLE
problem with Id

### ISSUE THREAD

**Issue by vAhyThe** [visualfanatic/vue-svg-loader#24]
hi,
is there some possibilities to make random generated id. Because without it svg images collide together.
thx

**Comment by visualfanatic** [comment]
Yes, but first of all you have to use `v0.5.0`, then you just need to adjust the loader options a bit, like so:
```diff
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'vue-svg-loader',
+       options: {
+         svgo: {
+           plugins: [
+             { prefixIds: true },
+           ],
+         },
+       },
      },
    ],
  },
}
```

If you want to customize generated IDs, you can pass a function instead of `true` to the `prefixIds` plugin. For example, if you want to generate IDs that are prefixed by the SVG file name, you can do like that:
```diff
+ const { basename } = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'vue-svg-loader',
        options: {
          svgo: {
            plugins: [
-             { prefixIds: true },
+             {
+               prefixIds: {
+                 prefix: (node, { path }) => basename(path, '.svg'),
+                 delim: '-',
+               },
+             },
            ],
          },
        },
      },
    ],
  },
}
```

**Comment by vAhyThe** [comment]
thx this work like charm, btw also create class on main `svg` if there png image inside

**Comment by visualfanatic** [comment]
> also create class on main svg if there png image inside

@vAhyThe could you explain a little bit more what do you mean?

**Comment by vAhyThe** [comment]
@visualfanatic 

`class="pin-Select-address__icon`
![image](https://user-images.githubusercontent.com/6084353/37035217-17889690-214c-11e8-9e57-27bd4878f034.png)
