### ISSUE TITLE
Is vue-svg-loader actively maintained?

### ISSUE THREAD

**Issue by sam3d** [visualfanatic/vue-svg-loader#36]
Hi @visualfanatic,

I noticed that `vue-svg-loader` doesn't appear to be actively maintained. I totally understand, as open source projects can often be a pain to manage.

I'd love to offer to be a maintainer of this module and oversee day-to-day pull requests and issues. Let me know what your thoughts are!

Sam

**Comment by visualfanatic** [comment]
Hello @sam3d!
I know that things seem to be progressing slowly, but once I am done working on the documentation (using vuepress) I will work on the issues & PRs. Currently I am writing the FAQ/examples section where I plan to cover the issues we had and how to solve them with pure Vue/Vue CLI and also Nuxt.js.

I appreciate your concerns, I will keep your offer in mind, but you should see the new docs/package version soon.

Thank you

**Comment by sam3d** [comment]
Hey!

That's absolutely alright, thank you for keeping us in the loop 🙂 

Good luck with everything! Eager to see what you've got in the works!
