### ISSUE TITLE
Not working with Nuxt.js

### ISSUE THREAD

**Issue by FistMeNaruto** [visualfanatic/vue-svg-loader#41]
Hi!

I have tried doing everything described in documentation, but I can't get vue-svg-loader to work with Nuxt.js

I get this error:
```
vue.runtime.esm.js:587 [Vue warn]: Invalid Component definition: data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjEwMCIgd2lkdGg9IjEwMCI+CiAgPGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDAiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMyIgZmlsbD0icmVkIiAvPgo8L3N2Zz4g

found in

---> <Pages/index.vue> at pages/index.vue
       <Nuxt>
         <Default> at layouts/default.vue
           <Root>
```

For some reason svg gets converted to base64 even though I removed it from url-loader test regex:

```js
const svgRule = config.module.rules.find(
          rule => rule.loader === "url-loader"
        );

        svgRule.test = /\.(png|jpe?g|gif)$/;

        config.module.rules.push({
          test: /\.svg$/,
          loader: "vue-svg-loader"
        });
```

Here is a repo for reproduction:

[FistMeNaruto/vue-svg-loader-test](https://github.com/FistMeNaruto/vue-svg-loader-test)

**Comment by FistMeNaruto** [comment]
Solved in nuxt/nuxt.js#3763

**Comment by Triloworld** [comment]
Don't close issue as It is actual for new Nuxt 2.0 and Webpack 4

```
extend (config, { isDev, isClient }) {
      if (isDev) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/
        });
      }

      config.module.rules.forEach((rule) => {
        if (rule.test.toString() === '/\\.(png|jpe?g|gif|svg|webp)$/') {
            rule.oneOf = [
            {
              loader: 'vue-svg-loader',
              resourceQuery: /\?inline/i,
              options: {
                svgo: {
                  plugins: [
                    { removeDoctype: true },
                    { removeComments: true },
                    { prefixIds: true },
                  ],
                },
              },
            }
          ].concat(rule.use);
          delete rule.use;
        }
      });
    }
```

Why?
rule.use is more important and by default as Nuxt 2.0 and Webpack 4
I concat new version to old so no settings are remove, just added to "oneOf" to support multiple loaders. Using "resourceQuery: /\?inline/i," i can distinguish between component and just file.

**Comment by visualfanatic** [comment]
> so no settings are remove

Unfortunately there is no way around modifying the loader config, here is an example that works for both Next 1.x and 2.x:
https://vue-svg-loader.netlify.com/faq.html#how-to-use-both-inline-and-external-svgs
