### ISSUE TITLE
vue-svg-loader > 0.5.0   // not work

### ISSUE THREAD

**Issue by mini-web** [visualfanatic/vue-svg-loader#44]
/ / package.json
{  
......
......
"dependencies": {
    "axios": "^0.18.0",
    "es6-shim": "^0.35.3",
    "moment": "^2.22.2",
    "lodash": "^4.17.10",
    "proxy-polyfill": "^0.3.0",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "@vue/eslint-config-standard": "^3.0.0-rc.3",
    "cross-env": "^5.1.6",
    "element-ui": "^2.4.1",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "vue-svg-loader": "^0.7.0",
    "vue-template-compiler": "^2.5.17"
  },
......
......
}

// vue-cli3    vue.config.js
const path = require('path')

module.exports = {
......
......
  chainWebpack: config => {
    config.plugin('html').tap(args => {
      args[0].chunksSortMode = 'none'
      return args
    })

    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()
    svgRule.use('vue-svg-loader').loader('vue-svg-loader')
  }
}
----------------------------------

vue-svg-loader <= 0.5.0   //  program runs well

vue-svg-loader > 0.5.0   //  not work

**Comment by visualfanatic** [comment]
@mini-web could you provide the error you are having? Could you also attach the SVG you are using?

**Comment by visualfanatic** [comment]
@mini-web
