### ISSUE TITLE
Selectively import inline SVG?

### ISSUE THREAD

**Issue by hdodov** [visualfanatic/vue-svg-loader#46]
Using this plugin, every SVG I import is interpreted for inline use. However, can I somehow make Vue CLI import an SVG the regular way? I want to use the path to an SVG in an `<img>` tag's `src` that is dynamic, the same way described [here](https://github.com/vuejs-templates/webpack/issues/450). How can this happen? If it can't, could you please implement this functionality?

**Comment by visualfanatic** [comment]
You can already do that, here is FAQ section with the solution:
https://vue-svg-loader.js.org/faq.html#how-to-use-both-inline-and-external-svgs

**Comment by hdodov** [comment]
Yeeeeeesssssssss! Thank you so very much!
