### ISSUE TITLE
Ability to add <title> and <description> within Vue templates

### ISSUE THREAD

**Issue by joelworsham** [visualfanatic/vue-svg-loader#55]
It would be fantastic if we could add the `<title>` and/or `<description>` tags into the `<svg>` itself, based on the context it's used in. Sometimes the title will be different for the icon, based on the context.

I would say either just allowing us to slot in content to the SVG or accept those props would be amazing.
```
<template>
  <MySvg>
    <title>Some Unique Title</title>
    <description>A really cool description about this specific context</description>
  </MySvg>
</template>
```
OR
```
<template>
  <MySvg
    title="Some Unique Title"
    description="A really cool description about this specific context"
  />
</template>
```

What do you think?

**Comment by joelworsham** [comment]
Apologies for not getting back to you on this, but thanks so much for implementing it!

**Comment by daverogers** [comment]
I'm on version `v.0.16.0` and adding "title" to the SVG isn't working, not sure if that piece was implemented or it requires `<title>` to be in the SVG already?

```vue
<IconDelete class="icon-delete" title="Delete" />
```

I ended up having to wrap the SVG in a span to attach the title, which isn't the end of the world but not as clean obviously:
```vue
<span title="Delete">
    <IconDelete class="icon-delete" />
</span>
```
