### ISSUE TITLE
Removes viewbox

### ISSUE THREAD

**Issue by RainArro** [visualfanatic/vue-svg-loader#58]
Before vue-svg-loader my svg looks like this.  
```
<svg xmlns="http://www.w3.org/2000/svg" width="59.225" height="15" viewBox="0 0 59.225 15">
```
When i include it as a vue component it removes viebox. I can not scale my svg without viewbox. 

```
<svg xmlns="http://www.w3.org/2000/svg" width="59.225" height="15">
```

**Comment by visualfanatic** [comment]
@RainArro have you checked @FistMeNaruto solution? Just disable the `removeViewBox` SVGO plugin and you should be fine.

**Comment by RainArro** [comment]
Thank you :)

**Comment by nicooprat** [comment]
Usage with Vue CLI:

```
...
.loader('vue-svg-loader')
.options({
  svgo: {
    plugins: [{ removeDimensions: true }, { removeViewBox: false }]
  }
})
...
```

[Complete list of SVGO options](https://github.com/svg/svgo/blob/master/.svgo.yml).

**Comment by KaliaJS** [comment]
Why the choice to remove the viewBox if it's present ?

**Comment by lights0123** [comment]
@KaliaJS it reduces size by a view bytes, which is the point of SVGO.
