### ISSUE TITLE
support vue-2.6

### ISSUE THREAD

**Issue by gitivon** [visualfanatic/vue-svg-loader#66]
Error:

Vue packages version mismatch:

- vue@2.6.2
- vue-template-compiler@2.5.17

**Comment by visualfanatic** [comment]
Hello @gitivon, please update the `vue-svg-loader` package to `0.12.0` and you should be good to go.

**Comment by gitivon** [comment]
thx

**Comment by trygveaa** [comment]
Can you push the commit and release to github too?

**Comment by lqs469** [comment]
In my case:
- vue@2.6.11
- vue-template-compiler@2.6.12
- vue-svg-loader@0.16.0

Still throw this error, So I downgrade the `vue-svg-loader` to 0.12.0, and fix it.

**Comment by damianstasik** [comment]
@lqs469 could you check `vue-svg-loader@beta` with `vue-loader` instead of `babel-loader`? Please take a look at the readme.

**Comment by lqs469** [comment]
> @lqs469 could you check `vue-svg-loader@beta` with `vue-loader` instead of `babel-loader`? Please take a look at the readme.

I reinstall `vue-svg-loader@beta`(0.17.0-beta.1 actually) with `vue-loader` just like `README`. And it works well. I think you have fixed it in beta version.
