### ISSUE TITLE
Cypress issue in 0.12.0

### ISSUE THREAD

**Issue by michalsnik** [visualfanatic/vue-svg-loader#68]
Hey Damian!

I just installed 0.12.0 and everything works fine, except Cypress in headless mode. The error I'm getting is:

```
Uncaught SyntaxError: Unexpected token ...
This error originated from your application code, not from Cypress.
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
https://on.cypress.io/uncaught-exception-from-application
```

Downgrading to 0.11.0 seems to fix the problem. So it looks like the code generated by the loader or one of its dependencies produces Object rest spread operator that might not work in headless mode without extra transpilation.

**Comment by appinteractive** [comment]
I have the exact same issue!

**Comment by sotaan** [comment]
Me too using vue cli 3

**Comment by grount** [comment]
Any update on this?

**Comment by honzabilek4** [comment]
I believe it's the same issue as here https://github.com/visualfanatic/vue-svg-loader/issues/76, cause the code in one of it's dependencies doesn't get transpiled and thus doesn't work in some browsers.
