### ISSUE TITLE
Met 'Cannot find module' problem using ts

### ISSUE THREAD

**Issue by GodofHope** [visualfanatic/vue-svg-loader#72]
# latest

Oh i found [faq use in typescript](https://vue-svg-loader.js.org/faq.html#how-to-use-this-loader-with-typescript)
Could Anyone tell me where I need to put this code?

Is adding a index.d.ts file in the module path and pasting the code in it right?

```ts
declare module '*.svg' {
  const content: any;
  export default content;
}

export = module
```

Then why am I still ctaching problems?

---

I install the module,and I found 
![image](https://user-images.githubusercontent.com/33315834/53295188-05995a80-3831-11e9-9d79-e7324a50a586.png)
a red underline.

All the modules are the latest, I got vue @2.6.7 and vue-svg-loader@0.12.0. My cli version is 3.4.1.I don't know what goes wrong

Here are my config files，I  tryed several svg.

vue.config.js
```js
module.exports = {
  chainWebpack: config => {
    const svgRule = config.module.rule('svg');

    svgRule.uses.clear();

    svgRule.use('vue-svg-loader').loader('vue-svg-loader');
  }
};
```

webpack.config.js

```js
module.exports = {
  module: {
    rules: [
      {
        loader: 'vue-svg-loader',
        test: /\.svg$/u
      }
    ]
  }
};
```

**Comment by GodofHope** [comment]
All the modules are the latest, I got vue @2.6.7 and vue-svg-loader@0.12.0. My cli version is 3.4.1.

I don't know what goes wrong

**Comment by GodofHope** [comment]
Could the author make a official type file and publish as @types/vue-svg-loader please? I really knew nothing about generate an d.ts file

**Comment by omniait** [comment]
I've solved this way, I'm using vue-cli, note that inline svgs (`import "file.svg?inline"`) still throw errors:
./src/shims-svg.d.ts
```ts
declare module '*.svg' {

import Vue from 'vue';

export default Vue;
}
```
./vue.config.js
```js
  chainWebpack: config => {
    const svgRule = config.module.rule("svg");

    svgRule.uses.clear();

    svgRule.use("vue-svg-loader").loader("vue-svg-loader");
  }
```
./src/components/Example.vue
```vue
<template>
  <logo />
</template>
<script lang="ts">
import Vue from 'vue';
import Logo from '@/assets/sbm_min_logo.svg';

export default Vue.extend({
  data() {
    return {
    };
  },
  components: {
    Logo,
  },
});
</script>
```

**Comment by WraithKenny** [comment]
This basically means I can't use this package.
