### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by mykone** [visualfanatic/vue-svg-loader#78]
Hello, thanks for creating this component, but I am unable to get it working in my setup. Here's my exception:

```
Failed to compile.
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type.
|             staticStyle,
|             attrs = {},
|             ...rest
|           } = data;
```

Here's my usage:
```
import GearsIcon from 'icons/settings.svg';
```

Here's my Webpack Config
```
//Inside webpack.parts.js
exports.loadImages = ({ include, exclude, options } = {}) => ({
  module: {
    rules: [
      {
        test: /\.(png|jpg|svg)$/,

        include,
        exclude,

        use: {
          loader: 'url-loader',
          options
        }
      }
    ]
  }
})

exports.loadSvgIcon = ({ include, exclude, options } = {}) => ({
  module: {
    rules: [
      {
        test: /\.svg$/,

        include,
        exclude,

        use: {
          loader: 'vue-svg-loader',
          options
        }
      }
    ]
  }
});

//Inside main webpack.config.js file
parts.loadSvgIcon({ include: [paths.app + '/icons'] }),
parts.loadImages({ include: [paths.admin, paths.app], exclude: [paths.app + '/icons'] }),
```

I'm not sure what I am doing wrong, it seems as if the loader is loading, but maybe another loader ins interfering with the string output of the loader. I am using Vue 2.6.9

Any help would be great. Thanks a lot.

**Comment by mykone** [comment]
Seems to be a loader issue for sure.. I used *svg-to-vue-component/loader* and it works fine.

**Comment by b12k** [comment]
Same issue in Edge and IE11.
`SCRIPT1028: SCRIPT1028: Expected identifier, string or number`
Looks like it is related to `spread` operator.
Which is not getting transpiled.

**Comment by andrey-hohlov** [comment]
solution https://github.com/visualfanatic/vue-svg-loader/issues/63#issuecomment-463114598

**Comment by exeptionerror** [comment]
[[Solved] Module parse failed: Unexpected token (763:13) in VueJs
](https://exerror.com/module-parse-failed-unexpected-token-76313-in-vuejs/)
