### ISSUE TITLE
svg-to-vue dependency using spread syntax which doesn't compiled

### ISSUE THREAD

**Issue by zslucky** [visualfanatic/vue-svg-loader#80]
I got `Uncaught SyntaxError: Unexpected token ...` in some browsers, like Chrome58, is it a way to use a compatible version?

**Comment by MattCCC** [comment]
Hello, I get similar error. Looks like UglifyJs cannot parse vue-svg-loader syntax:

```
    ERROR in js/3.ae7f96b062b8e993ad31.js from UglifyJs
    Unexpected token: punc «(» [./node_modules/vue-svg-loader??ref--1-0!./src/svg/close.svg:4,0][js/3.ae7f96b062b8e993ad31.
js:11,14]


```

**Comment by MattCCC** [comment]
Hello, I have very similar problem when trying to build with Webpack 4:
```
    ERROR in js/40.3c2d0cc4d605b2b10d6f.js from UglifyJs
    Unexpected token: punc «(» [./node_modules/vue-svg-loader??ref--1-0!./src/svg/new/arrow-right.svg:4,0][js/40.3c2d0cc4d6
05b2b10d6f.js:11,14]
```

Any idea how can I fix it?

**Comment by kamwing** [comment]
same problem

**Comment by GodofHope** [comment]
Same problem

**Comment by grount** [comment]
+1

**Comment by youcanping** [comment]
+1 😿，害我找了好久

**Comment by zslucky** [comment]
I just fork the loader, update code manually, remove the unwanted syntax, or use another loader which I found it pass the code to vue-loader for further compile.

**Comment by GodofHope** [comment]
It can be fixed by configuring vue.config.js file correctly, I will paste my solution code later.

**Comment by youcanping** [comment]
In vue.config.js fix like this.

```js
const svgRule = config.module.rule('svg');
    svgRule.uses.clear();
    svgRule
      .use('babel-loader')
      .loader('babel-loader')
      .end()
      .use('vue-svg-loader')
      .loader('vue-svg-loader')
      .options({
        svgo: {
          plugins: [
            { removeDoctype: true },
            { removeComments: true },
            { removeViewBox: false }
          ],
          removeViewBox: false,
        },
      })
      .end()
```

**Comment by GodofHope** [comment]
Thx!
btw what does `svgo` mean

**Comment by hecktarzuli** [comment]
@GodofHope svgo is an svg optimizer.  https://github.com/svg/svgo

**Comment by ptandler** [comment]
I thin youcanping's config should really be very prominent in the docs, so I added it to the README, see pull request https://github.com/visualfanatic/vue-svg-loader/pull/93
