### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by FilipaSimao** [visualfanatic/vue-svg-loader#81]
I got this error "Non-whitespace before first tag." on Vue-CLI 3.

### Component
` <img :src="require(`@/assets/${logo}`)" :alt="name">`

### Vue.config.js
```
  chainWebpack: config => {
    const svgRule = config.module.rule("svg");
    svgRule.uses.clear();
    svgRule.use("vue-svg-loader").loader("vue-svg-loader");
  },
```

**Comment by watsuyo** [comment]
@FilipaSimao 
I face the same problem. Was there a solution?

**Comment by TheDutchCoder** [comment]
Same thing for me, this repo seems inactive :(

**Comment by marcel-dancak** [comment]
I think you guys are just missing 'babel-loader' part in your config, like it is shown in current documentation.

**Comment by TheDutchCoder** [comment]
Nope, I use Babel loader in my setup.

**Comment by marcel-dancak** [comment]
I have just created a fresh Vue app with Vue CLI and used exact config as @FilipaSimao without any problem. However, I have imported and used my svg file as regular Vue component, which was properly rendered as `<svg>` element. If you want to also keep an option to use svg file in `<img>` element, which require `file-loader`, then you can use this config

**vue.config.js**
```javascript
module.exports = {
  chainWebpack: config => {
    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()

    config.module
      .rule('svg')
      .oneOf('inline-svg')
        .resourceQuery(/inline/)
        .use('babel')
          .loader('babel-loader')
          .end()
        .use('vue-svg-loader')
          .loader('vue-svg-loader')
          .end()
        .end()
      .oneOf('file')
        .use('file-loader')
          .loader('file-loader')
          .end()
        .end()
  }
}
```
and use it in your component (notice `?inline` param in import to use `vue-svg-loader`)
```vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <img alt="SVG logo" src="./assets/logo.svg">
    <svg-logo/>
  </div>
</template>

<script>
import SvgLogo from './assets/logo.svg?inline'

export default {
  name: 'App',
  components: {
    SvgLogo
  }
}
</script>
```

I have also tried to remove `babel-loader` from the config and it was working, so now I don't really know what is exact reason of this error message. But I have definitely came across this error, however it could be related to svg-sprite-loader which I also often use.

**Comment by ndh103** [comment]
Thanks @marcel-dancak , I am able to use your config, just a small update that I use 'vue-loader' instead of 'babel-loader'

```
const svgRule = config.module.rule("svg")
  svgRule.uses.clear()

  config.module
    .rule("svg")
    .oneOf("inline-svg")
    .resourceQuery(/inline/)
    .use("vue-loader")
    .loader("vue-loader") // or `vue-loader-v16` if you are using a preview support of Vue 3 in Vue CLI
    .end()
    .use("vue-svg-loader")
    .loader("vue-svg-loader")
    .end()
    .end()
    .oneOf("file")
    .use("file-loader")
    .loader("file-loader")
    .end()
    .end()

```

**Comment by FilipaSimao** [comment]
I added the following code in my **vue.config.js** :
```
module.exports = {
  chainWebpack: config => {
    config.module.rules.delete("svg");
  },
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.svg$/,
          loader: "vue-svg-loader"
        },
        {
          test: /\.(jpg|jpeg|woff|woff2|eot|ttf)?$/,
          use: {
            loader: "url-loader",
            options: {
              limit: 100000
            }
          }
        }
      ]
    }
  }
};
```
