### ISSUE TITLE
duplicate svg files

### ISSUE THREAD

**Issue by Marrie89** [visualfanatic/vue-svg-loader#90]
Hello

I am having a problem using. When I connect svg as components and there are more than 1 of them - instead of loading all svg into my html - the output of my svg code is simply duplicated several times. Please explain what the problem is - the Internet has not found a solution.
thanks for the help.
 http://joxi.ru/V2VldakCdRKdKr
http://joxi.ru/krD3j8esKqJKdA
http://joxi.ru/D2Pq34RSqykqBA

**Comment by nakajmg** [comment]
I also encountered the same problem.

In my case, same `id` attribute value was exists in imported svg.

**Comment by Alexg10** [comment]
Yes, look a the `id` or the `class` inside your svg. It must be unique to not use the same style.
