### ISSUE TITLE
SVG classes are not fully merged in SSR

### ISSUE THREAD

**Issue by danielroe** [visualfanatic/vue-svg-loader#94]
A svg with an inline class that is then assigned a class within the parent component, it is not merged on SSR (Nuxt) - or, rather, it has two class attributes, one of which is merged. The result is an unattractive flash on load when the classes are merged in the browser. This behaviour is not present in `vue-svg-loader@0.11`.

`my-svg.svg`:
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 169.6 169.6" class="test">
  ...
</svg>
```

`ParentComponent.vue`:
```vue
<template>
  <MySvg :class="$style.thisClass" />
</template>
```

Result (in SSR):
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 169.6 169.6" class="test" class="test thisClass_4ad82">
  ...
</svg>
```

Workaround is to remove classes from the `.svg` files.

**Comment by visualfanatic** [comment]
Please try updating the package and let me know if that works.

**Comment by danielroe** [comment]
Will do :smiley: :+1:

**Comment by danielroe** [comment]
@visualfanatic It doesn't actually solve this for me. I apologise for not adding a repro the first time round, however, and have now done so: https://github.com/danielroe/repro-vue-svg-loader

I may also take a look at this myself later.

**Comment by visualfanatic** [comment]
@danielroe I found the issue and released a new version with the fix, please try updating to `vue-svg-loader@0.15.0`.

**Comment by danielroe** [comment]
@visualfanatic Hm. Still giving me a mismatch.

**Comment by danielroe** [comment]
Sorry - my fault, I had linked to my in-development version of vue-svg-loader!
