### ISSUE TITLE
Importing SVG with symbols

### ISSUE THREAD

**Issue by maximelafarie** [visualfanatic/vue-svg-loader#96]
I would like to import SVGs from a `.svg` file that contains many `<symbol>`.
But I can't find how import them all through a unique import instruction. 

E.g.: I'm trying to import them like this:

```ts
public svg = require('@/assets/symbols.svg');
```

Then if I try to display it into the view I got this:
```
<pre>{{ svg }}</pre>

<!-- Displays the message below after rendering -->
[object Module]
```
I don't know how to figure it out.

Regards! 🖖

**Comment by sandrina-p** [comment]
I'm having the same issue... have you found a solution?

**Comment by maximelafarie** [comment]
For the moment I'm importing SVGs at a higher level of the app instead of inside the vueJS app. So I can call each icon from Vue app.
But that's really not handy at all... 😕

**Comment by visualfanatic** [comment]
Hey @maximelafarie, could you share your SVG so I can try to repro this issue?
