### ISSUE TITLE
After loading the id attribute is missing

### ISSUE THREAD

**Issue by Rednas83** [visualfanatic/vue-svg-loader#97]
After loading a SVG file the id attributes are missing from the loaded SVG file.

Before:
![image](https://user-images.githubusercontent.com/25219229/65425177-ac68c800-de0d-11e9-97f5-3097d725f90f.png)
After:
![image](https://user-images.githubusercontent.com/25219229/65426332-4e89af80-de10-11e9-8380-b2b8cc94d947.png)

Is there any way to load the svg together with the id attributes?

**Comment by 2xAA** [comment]
Hey @Rednas83, came here with the same problem.
Using this option with SVGO in your webpack config keeps the IDs: https://github.com/visualfanatic/vue-svg-loader/issues/60#issuecomment-441359653

```
{
  test: /\.svg$/,
  loader: 'vue-svg-loader',
  options: {
    svgo: {
      plugins: [
        { cleanupIDs: false },
      ],
    },
  },
},
```

If your project is bootstrapped using the Vue CLI and you're using `vue-cli-plugin-svg-loader`, you can use this in your `vue.config.js`:

```
pluginOptions: {
  svgLoader: {
    svgo: {
      plugins: [{ cleanupIDs: false }]
    }
  }
}
```

**Comment by visualfanatic** [comment]
Please follow @2xAA solution, IDs are "cleaned" by default by SVGO.
